name: Run Nomad Job via SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Submit Job to Nomad API
        env:
          NOMAD_ADDR: "http://45.86.183.34:4646"  # Адрес вашего Nomad сервера
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }} # Токен с правами submit-job
        run: |
          jq -Rsc '{ JobHCL: ., Canonicalize: true }' ./jobs/example_jobs.hcl > ./jobs/example_jobs.json
          curl \
            -X POST\
            -H "X-Nomad-Token: $NOMAD_TOKEN" \
            -H "Content-Type: application/json" \
            --data @./jobs/example_jobs.json \
            http://45.86.183.34:4646/v1/job/docker-example_compose-up-for2VM

          
