name: Run Nomad Job via SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy Nomad job file
        uses: appleboy/scp-action@master
        with:
            host:     45.86.183.34
            port:     22
            username: root
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            source:   jobs/example_jobs.hcl
            target:   /tmp/
            strip_components: 1

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
            host: 45.86.183.34
            username: root
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
              
              export NOMAD_TOKEN=${{ secrets.NOMAD_TOKEN }}
              export NOMAD_ADDR=http://45.86.183.34:4646/
              nomad acl token self
              nomad job run /tmp/example_jobs.hcl
