name: Run Nomad Job

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Nomad namespace (имя папки + название namespace)'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup HashiCorp Nomad
        uses: hashicorp/setup-nomad@v1.0.0
        with:
          version: '1.10.2' 
          
      - name: Submit Job to Nomad API
        env:
          NOMAD_ADDR: "http://45.86.183.34:4646"  
          NOMAD_TOKEN: ${{ secrets.NOMAD_ONLY_JOB_TOKEN }}
          NAMESPACE: ${{ github.event.inputs.namespace }}
        run: |
          JOB_PATH=$(find "${NAMESPACE}" -maxdepth 1 -type f -name '*.hcl' | head -n1)
          echo $JOB_PATH
          nomad job validate "$JOB_PATH"
          
          nomad job run plan\
            -namespace="$NAMESPACE" \
            "$JOB_PATH"
          nomad --version


          
