name: Run Nomad Job via SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Настройка SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Здесь сразу пропишем хост и порт
          ssh-keyscan -p 2222 45.86.183.34 >> ~/.ssh/known_hosts

      - name: Копируем Nomad job на сервер
        run: |
          # SCP с прямым указанием порта и хоста
          scp -P 2222 jobs/example_jobs.hcl root@45.86.183.34:/tmp/

      - name: Запускаем Nomad job
        env:
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
        run: |
          # SSH с тем же хостом/портом и запуск nomad job
          ssh -p 2222 root@45.86.183.34 \
            "export NOMAD_TOKEN=$NOMAD_TOKEN && nomad job run /tmp/example_jobs.hcl"
