name: Run Nomad Job

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Nomad namespace (имя папки + название namespace)'
        required: true
      compose_path:
        description: 'Куда сохранить новый compose файл)'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup HashiCorp Nomad
        uses: hashicorp/setup-nomad@v1.0.0
        with:
          version: '1.10.2' 
          
      - name: Submit Job to Nomad API
        env:
          NOMAD_ADDR: "http://45.86.183.34:4646"  
          NOMAD_TOKEN: ${{ secrets.NOMAD_ONLY_JOB_TOKEN }}
          NAMESPACE: ${{ github.event.inputs.namespace }}
          JOB_PATH: "./job_send_new_compose-file/new_compose_file.hcl"
        run: |                
          nomad job validate "$JOB_PATH"
          nomad job run \
            -namespace="$NAMESPACE" \
            -var="namespace=$NAMESPACE" \
            -var="compose_path=$compose_path" \
            "$JOB_PATH"
          


          
