name: Run Nomad Job via SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to VM using password
        uses: appleboy/ssh-action@v1
        with:
          host: 45.86.183.34        # ваш хост
          port: 2222               # ваш порт
          username: root           # логин
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 1m
          script: |
            whoami
            hostname
            uptime
