name: Run Nomad Job via SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
            host: 45.86.183.34
            username: root
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: whoami
