name: Run Nomad Job via SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
            host: 45.86.183.34
            username: root
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
              # Сначала копируем файл (альтернатива scp)
              cat > /root/example_jobs.hcl << 'EOF'
              $(cat jobs/example_jobs.hcl)
              EOF
              
              # Проверяем что файл скопировался
              ls -la /root/example_jobs.hcl
              cat /root/example_jobs.hcl
              
              export NOMAD_TOKEN=${{ secrets.NOMAD_TOKEN }}
              nomad job run /root/example_jobs.hcl
