name: Run Nomad Job via SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
        run: |
          # Настройка SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Копируем job-файл на сервер
          scp -o StrictHostKeyChecking=no ./jobs/example_jobs.hcl root@45.86.183.34:/tmp/

          # Запускаем job с передачей NOMAD_TOKEN
          ssh -o StrictHostKeyChecking=no root@45.86.183.34 \
            "export NOMAD_TOKEN=$NOMAD_TOKEN && nomad job run /tmp/example_jobs.hcl"
