name: Run Nomad Job via SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
            host: 45.86.183.34
            username: root
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            sync: |
            source: jobs/example_jobs.hcl
            target: /root
            # а вот тут на сервере сразу запускаете nomad
            script: |
              export NOMAD_TOKEN=${{ secrets.NOMAD_TOKEN }}
              nomad job run /root/example_jobs.hcl
