name: Run Nomad Job via SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
            host: 45.86.183.34
            username: root
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
              ## Создаем временный файл
              TEMP_FILE=$(mktemp)
              
              # Копируем содержимое в файл на сервере
              cat > "$TEMP_FILE" << 'NOMAD_JOB'
              $(cat jobs/example_jobs.hcl)
              NOMAD_JOB
              
              # Проверяем содержимое файла
              echo "File content:"
              cat "$TEMP_FILE"
              echo -e "\nFile size: $(wc -c < "$TEMP_FILE") bytes
              
              export NOMAD_TOKEN=${{ secrets.NOMAD_TOKEN }}
              nomad job run /root/example_jobs.hcl
